name: Push esp_secure_cert_mgr to Espressif Component Service

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload esp_secure_cert_mgr to component service
        uses: espressif/github-actions/upload_components@master
        with:
          name: esp_secure_cert_mgr
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
